apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: discovery-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-pod
  template:
    metadata:
      labels:
        app: discovery-pod
    spec:
      containers:
      - name: discovery
        image: getdiscovery:1
        imagePullPolicy: Never
        volumeMounts:
        - name: kind-compositions-volume
          mountPath: /etc/kubediscovery
        env:
        - name: KIND_COMPOSITION_FILE
          value: /etc/kubediscovery/kind_compositions.yaml
      volumes:
      - name: kind-compositions-volume
        configMap:
          name: kind-compositions-config-map


