apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-discovery-apiserver
  namespace: discovery
  labels:
    apiserver: "true"
spec:
  replicas: 1
  selector:
    apiserver: "true"
  template:
    metadata:
      labels:
        apiserver: "true"
    spec:
      serviceAccountName: apiserver
      containers:
      - name: kube-discovery-apiserver
        image: kube-discovery-apiserver:latest
        imagePullPolicy: Never
        command: [ "/kube-discovery-apiserver", "--etcd-servers=http://localhost:2379" ]
        volumeMounts:
        - name: kind-compositions-volume
          mountPath: /etc/kubediscovery
        env:
        - name: KIND_COMPOSITION_FILE
          value: /etc/kubediscovery/kind_compositions.yaml
      - name: etcd
        image: quay.io/coreos/etcd:v3.2.18
      volumes:
        - name: kind-compositions-volume
          configMap:
            name: kind-compositions-config-map
